In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef
)

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Grid stability test dataset.csv to Grid stability test dataset.csv

In [ ]:
file_name = list(uploaded.keys())[0]

data = pd.read_csv('/content/Grid stability test dataset.csv')

print("Dataset loaded successfully!")
print("Dataset size:", data.shape)

Dataset loaded successfully!
Dataset size: (10000, 14)

In [ ]:
data.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [ ]:
print(data.columns)

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stab', 'stabf'],
      dtype='object')

In [ ]:
data.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [ ]:
print(data["stabf"].value_counts())

stabf
unstable    6380
stable      3620
Name: count, dtype: int64

In [ ]:
X = data.drop(["stab", "stabf"], axis=1)

y = data["stabf"]

print("Number of input features:", X.shape[1])
print("Number of samples:", X.shape[0])

Number of input features: 12
Number of samples: 10000

In [ ]:
encoder = LabelEncoder()

y = encoder.fit_transform(y)

print("Target classes:")
print(encoder.classes_)

Target classes:
['stable' 'unstable']

In [ ]:
print("0 =", encoder.classes_[0])
print("1 =", encoder.classes_[1])

0 = stable
1 = unstable

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 8000
Testing samples: 2000

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

print("Feature scaling completed!")

Feature scaling completed!

In [ ]:
logistic_model = LogisticRegression(max_iter=1000)

logistic_model.fit(X_train_scaled, y_train)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

In [ ]:
logistic_prediction = logistic_model.predict(X_test_scaled)

logistic_probability = logistic_model.predict_proba(X_test_scaled)[:, 1]

print("Predictions completed!")

Predictions completed!

In [ ]:
logistic_accuracy = accuracy_score(
    y_test,
    logistic_prediction
)

logistic_auc = roc_auc_score(
    y_test,
    logistic_probability
)

logistic_precision = precision_score(
    y_test,
    logistic_prediction
)

logistic_recall = recall_score(
    y_test,
    logistic_prediction
)

logistic_f1 = f1_score(
    y_test,
    logistic_prediction
)

logistic_mcc = matthews_corrcoef(
    y_test,
    logistic_prediction
)

In [ ]:
print("LOGISTIC REGRESSION RESULTS")
print("--------------------------------")
print("Accuracy  :", round(logistic_accuracy, 4))
print("AUC Score :", round(logistic_auc, 4))
print("Precision :", round(logistic_precision, 4))
print("Recall    :", round(logistic_recall, 4))
print("F1 Score  :", round(logistic_f1, 4))
print("MCC Score :", round(logistic_mcc, 4))

LOGISTIC REGRESSION RESULTS
--------------------------------
Accuracy  : 0.82
AUC Score : 0.892
Precision : 0.8408
Recall    : 0.8856
F1 Score  : 0.8626
MCC Score : 0.6039

In [ ]:
decision_tree = DecisionTreeClassifier(
    random_state=42
)

decision_tree.fit(X_train, y_train)

print("Decision Tree trained successfully!")

Decision Tree trained successfully!

In [ ]:
tree_prediction = decision_tree.predict(X_test)

tree_probability = decision_tree.predict_proba(X_test)[:, 1]

print("Decision Tree predictions completed!")

Decision Tree predictions completed!

In [ ]:
tree_accuracy = accuracy_score(
    y_test,
    tree_prediction
)

tree_auc = roc_auc_score(
    y_test,
    tree_probability
)

tree_precision = precision_score(
    y_test,
    tree_prediction
)

tree_recall = recall_score(
    y_test,
    tree_prediction
)

tree_f1 = f1_score(
    y_test,
    tree_prediction
)

tree_mcc = matthews_corrcoef(
    y_test,
    tree_prediction
)

In [ ]:
print("DECISION TREE RESULTS")
print("--------------------------------")
print("Accuracy  :", round(tree_accuracy, 4))
print("AUC Score :", round(tree_auc, 4))
print("Precision :", round(tree_precision, 4))
print("Recall    :", round(tree_recall, 4))
print("F1 Score  :", round(tree_f1, 4))
print("MCC Score :", round(tree_mcc, 4))

DECISION TREE RESULTS
--------------------------------
Accuracy  : 0.8495
AUC Score : 0.8369
Precision : 0.8818
Recall    : 0.8824
F1 Score  : 0.8821
MCC Score : 0.6741

In [ ]:
knn_model = KNeighborsClassifier(
    n_neighbors=5
)

knn_model.fit(X_train_scaled, y_train)

print("KNN model trained successfully!")

KNN model trained successfully!

In [ ]:
knn_prediction = knn_model.predict(X_test_scaled)

knn_probability = knn_model.predict_proba(X_test_scaled)[:, 1]

print("KNN predictions completed!")

KNN predictions completed!

In [ ]:
knn_accuracy = accuracy_score(
    y_test,
    knn_prediction
)

knn_auc = roc_auc_score(
    y_test,
    knn_probability
)

knn_precision = precision_score(
    y_test,
    knn_prediction
)

knn_recall = recall_score(
    y_test,
    knn_prediction
)

knn_f1 = f1_score(
    y_test,
    knn_prediction
)

knn_mcc = matthews_corrcoef(
    y_test,
    knn_prediction
)

In [ ]:
print("K-NEAREST NEIGHBOUR RESULTS")
print("--------------------------------")
print("Accuracy  :", round(knn_accuracy, 4))
print("AUC Score :", round(knn_auc, 4))
print("Precision :", round(knn_precision, 4))
print("Recall    :", round(knn_recall, 4))
print("F1 Score  :", round(knn_f1, 4))
print("MCC Score :", round(knn_mcc, 4))

K-NEAREST NEIGHBOUR RESULTS
--------------------------------
Accuracy  : 0.8625
AUC Score : 0.929
Precision : 0.8547
Recall    : 0.9451
F1 Score  : 0.8977
MCC Score : 0.698

In [ ]:
naive_bayes = GaussianNB()

naive_bayes.fit(X_train, y_train)

print("Gaussian Naive Bayes trained successfully!")

Gaussian Naive Bayes trained successfully!

In [ ]:
nb_prediction = naive_bayes.predict(X_test)

nb_probability = naive_bayes.predict_proba(X_test)[:, 1]

print("Naive Bayes predictions completed!")

Naive Bayes predictions completed!

In [ ]:
nb_accuracy = accuracy_score(
    y_test,
    nb_prediction
)

nb_auc = roc_auc_score(
    y_test,
    nb_probability
)

nb_precision = precision_score(
    y_test,
    nb_prediction
)

nb_recall = recall_score(
    y_test,
    nb_prediction
)

nb_f1 = f1_score(
    y_test,
    nb_prediction
)

nb_mcc = matthews_corrcoef(
    y_test,
    nb_prediction
)

In [ ]:
print("GAUSSIAN NAIVE BAYES RESULTS")
print("--------------------------------")
print("Accuracy  :", round(nb_accuracy, 4))
print("AUC Score :", round(nb_auc, 4))
print("Precision :", round(nb_precision, 4))
print("Recall    :", round(nb_recall, 4))
print("F1 Score  :", round(nb_f1, 4))
print("MCC Score :", round(nb_mcc, 4))

GAUSSIAN NAIVE BAYES RESULTS
--------------------------------
Accuracy  : 0.8445
AUC Score : 0.921
Precision : 0.8395
Recall    : 0.935
F1 Score  : 0.8847
MCC Score : 0.657

In [ ]:
random_forest = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

random_forest.fit(X_train, y_train)

print("Random Forest trained successfully!")

Random Forest trained successfully!

In [ ]:
rf_prediction = random_forest.predict(X_test)

rf_probability = random_forest.predict_proba(X_test)[:, 1]

print("Random Forest predictions completed!")

Random Forest predictions completed!

In [ ]:
rf_accuracy = accuracy_score(
    y_test,
    rf_prediction
)

rf_auc = roc_auc_score(
    y_test,
    rf_probability
)

rf_precision = precision_score(
    y_test,
    rf_prediction
)

rf_recall = recall_score(
    y_test,
    rf_prediction
)

rf_f1 = f1_score(
    y_test,
    rf_prediction
)

rf_mcc = matthews_corrcoef(
    y_test,
    rf_prediction
)

In [ ]:
print("RANDOM FOREST RESULTS")
print("--------------------------------")
print("Accuracy  :", round(rf_accuracy, 4))
print("AUC Score :", round(rf_auc, 4))
print("Precision :", round(rf_precision, 4))
print("Recall    :", round(rf_recall, 4))
print("F1 Score  :", round(rf_f1, 4))
print("MCC Score :", round(rf_mcc, 4))

RANDOM FOREST RESULTS
--------------------------------
Accuracy  : 0.924
AUC Score : 0.9806
Precision : 0.9226
Recall    : 0.9616
F1 Score  : 0.9417
MCC Score : 0.8342

In [ ]:
results = pd.DataFrame({

    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "K-Nearest Neighbour",
        "Gaussian Naive Bayes",
        "Random Forest"
    ],

    "Accuracy": [
        logistic_accuracy,
        tree_accuracy,
        knn_accuracy,
        nb_accuracy,
        rf_accuracy
    ],

    "AUC Score": [
        logistic_auc,
        tree_auc,
        knn_auc,
        nb_auc,
        rf_auc
    ],

    "Precision": [
        logistic_precision,
        tree_precision,
        knn_precision,
        nb_precision,
        rf_precision
    ],

    "Recall": [
        logistic_recall,
        tree_recall,
        knn_recall,
        nb_recall,
        rf_recall
    ],

    "F1 Score": [
        logistic_f1,
        tree_f1,
        knn_f1,
        nb_f1,
        rf_f1
    ],

    "MCC Score": [
        logistic_mcc,
        tree_mcc,
        knn_mcc,
        nb_mcc,
        rf_mcc
    ]
})

results = results.round(4)

print(results)

                  Model  Accuracy  AUC Score  Precision  Recall  F1 Score  \
0   Logistic Regression    0.8200     0.8920     0.8408  0.8856    0.8626
1         Decision Tree    0.8495     0.8369     0.8818  0.8824    0.8821
2   K-Nearest Neighbour    0.8625     0.9290     0.8547  0.9451    0.8977
3  Gaussian Naive Bayes    0.8445     0.9210     0.8395  0.9350    0.8847
4         Random Forest    0.9240     0.9806     0.9226  0.9616    0.9417

   MCC Score
0     0.6039
1     0.6741
2     0.6980
3     0.6570
4     0.8342

In [ ]:
results.to_csv(
    "ML_Classification_Results.csv",
    index=False
)

print("Results saved successfully!")

Results saved successfully!

In [ ]:
# One new test sample

new_sample = pd.DataFrame([{
    "tau1": 5,
    "tau2": 6,
    "tau3": 7,
    "tau4": 8,
    "p1": 3.0,
    "p2": -1.0,
    "p3": -1.2,
    "p4": -0.8,
    "g1": 0.6,
    "g2": 0.7,
    "g3": 0.8,
    "g4": 0.9
}])

print(new_sample)

   tau1  tau2  tau3  tau4   p1   p2   p3   p4   g1   g2   g3   g4
0     5     6     7     8  3.0 -1.0 -1.2 -0.8  0.6  0.7  0.8  0.9

In [ ]:
new_sample_scaled = scaler.transform(new_sample)

In [ ]:
# Logistic Regression
logistic_result = logistic_model.predict(new_sample_scaled)[0]

# Decision Tree
tree_result = decision_tree.predict(new_sample)[0]

# KNN
knn_result = knn_model.predict(new_sample_scaled)[0]

# Naive Bayes
nb_result = naive_bayes.predict(new_sample)[0]

# Random Forest
rf_result = random_forest.predict(new_sample)[0]

In [ ]:
print("Predictions for the new test sample")
print("--------------------------------------")

print("Logistic Regression :", encoder.inverse_transform([logistic_result])[0])
print("Decision Tree       :", encoder.inverse_transform([tree_result])[0])
print("K-Nearest Neighbour:", encoder.inverse_transform([knn_result])[0])
print("Naive Bayes         :", encoder.inverse_transform([nb_result])[0])
print("Random Forest       :", encoder.inverse_transform([rf_result])[0])

Predictions for the new test sample
--------------------------------------
Logistic Regression : unstable
Decision Tree       : unstable
K-Nearest Neighbour: unstable
Naive Bayes         : unstable
Random Forest       : unstable